# Generated by Django 2.2.24 on 2024-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240312_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordinfo',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
